# Generated by Django 5.0.2 on 2024-07-06 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('login', '0007_userprofile_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['-c_time', '-u_time'], 'verbose_name': '关键词', 'verbose_name_plural': '关键词'},
        ),
        migrations.AddField(
            model_name='keyword',
            name='u_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userprofile'),
        ),
    ]
