# Generated by Django 5.0.2 on 2024-07-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_keyword_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='u_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
