# Generated by Django 5.0.2 on 2024-07-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bloginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='key_word',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='key_word_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
