# Generated by Django 5.0.2 on 2024-07-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bloginfo_key_word_bloginfo_key_word_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='blog_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='like_count',
            field=models.CharField(default='', max_length=256),
        ),
    ]
