# Generated by Django 5.0.2 on 2024-07-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bloginfo_blog_url_bloginfo_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='sentiment',
            field=models.CharField(default='', max_length=256),
        ),
    ]
